version: '3'
networks:
  main: {}

services:
  client:
    build: ./client
    volumes:
      - ./client/src:/app/src
    networks:
      - main
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
      - REACT_APP_WEBSOCKET_URL=ws://localhost:3002
    entrypoint:
      - npm
      - run
      - start

  web_server:
    build: ./web-server
    volumes:
      - ./web-server:/app
    networks:
      - main
    ports:
      - 3001:3001
    depends_on:
      - cassandra
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=chat
      - POSTGRES_USER=chat_user
      - POSTGRES_PASSWORD=test
      - POSTGRES_DEBUG=true
      - SECRET=secret
    entrypoint:
      - npm
      - run
      - start

  ws_server:
    build: ./ws-server
    volumes:
      - ./ws-server:/app
    networks:
      - main
    ports:
      - 3002:3002
    depends_on:
      - cassandra
      - web_server
    entrypoint:
      - npm
      - run
      - start

  cassandra:
    build: ./db
    networks:
      - main
    ports:
      - 9160:9160
      - 9042:9042
    volumes:
      - ./db/scripts:/db-scripts
    environment:
      CASSANDRA_CLUSTER_NAME: chat

  postgres:
    image: postgres:10.3
    networks:
      - main
    ports:
      - 6432:5432
    environment:
      - POSTGRES_DB=chat
      - POSTGRES_USER=chat_user
      - POSTGRES_PASSWORD=test
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
