version: '3'
networks:
  main: {}

services:
  client:
    build: ./client
    volumes:
      - ./client/src:/app/src
    networks:
      - main
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_WEBSOCKET_URL=ws://localhost:3001
    entrypoint:
      - npm
      - run
      - start

  server:
    build: ./server
    volumes:
      - ./server:/app
    networks:
      - main
    ports:
      - 3001:3001
    depends_on:
      - cassandra
    entrypoint:
      - npm
      - run
      - start

  cassandra:
    build: ./db
    networks:
      - main
    ports:
      - 9160:9160
      - 9042:9042
    volumes:
      - ./db/scripts:/db-scripts
    environment:
      CASSANDRA_CLUSTER_NAME: chat
