version: '3'
networks:
  main: {}

services:
  client:
    build: ./client
    volumes:
      - ./client/src:/app/src
    networks:
      - main
    ports:
      - 3000:3000
    environment:
      - REACT_APP_HTTP_SERVER_URL=http://localhost:3001
      - REACT_APP_WEBSOCKET_SERVER_URL=ws://localhost:3001
    entrypoint:
      - npm
      - run
      - start

  server:
    build: ./server
    volumes:
      - ./server:/app
    networks:
      - main
    ports:
      - 3001:3001
    entrypoint:
      - npm
      - run
      - start
